### ISSUE TITLE
Cannot build on OSX 10.12

### ISSUE THREAD

**Issue by rjcoupe** [zone117x/node-cryptonote-pool#190]
```
In file included from ../src/main.cc:8:
In file included from ../src/cryptonote_core/cryptonote_basic.h:16:
In file included from ../src/serialization/binary_archive.h:15:
../src/common/varint.h:8:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^
5 errors generated.
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
```

This is `cryptonote-util` failing to build; has anyone found a solution?
